"""Create a compact local marketplace containing the AgentBoard plugin."""

from __future__ import annotations

import argparse
import json
import shutil
import tempfile
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
PLUGIN_NAME = "agent-board"
MARKETPLACE_NAME = "agentboard-local"


def _marketplace_payload() -> dict[str, object]:
    return {
        "name": MARKETPLACE_NAME,
        "interface": {"displayName": "AgentBoard local"},
        "plugins": [
            {
                "name": PLUGIN_NAME,
                "source": {
                    "source": "local",
                    "path": f"./plugins/{PLUGIN_NAME}",
                },
                "policy": {
                    "installation": "AVAILABLE",
                    "authentication": "ON_INSTALL",
                },
                "category": "Productivity",
            }
        ],
    }


def _is_owned_marketplace(path: Path) -> bool:
    marker = path / ".agents" / "plugins" / "marketplace.json"
    try:
        payload = json.loads(marker.read_text(encoding="utf-8"))
    except (FileNotFoundError, json.JSONDecodeError, OSError):
        return False
    return payload.get("name") == MARKETPLACE_NAME


def _copy_bundle(staging_root: Path) -> None:
    plugin_root = staging_root / "plugins" / PLUGIN_NAME
    plugin_root.mkdir(parents=True)

    shutil.copytree(PROJECT_ROOT / ".codex-plugin", plugin_root / ".codex-plugin")
    shutil.copy2(PROJECT_ROOT / ".mcp.json", plugin_root / ".mcp.json")
    shutil.copytree(PROJECT_ROOT / "hooks", plugin_root / "hooks")
    shutil.copytree(
        PROJECT_ROOT / "skills" / "agentboard-orchestrate",
        plugin_root / "skills" / "agentboard-orchestrate",
    )

    marketplace_path = staging_root / ".agents" / "plugins" / "marketplace.json"
    marketplace_path.parent.mkdir(parents=True)
    marketplace_path.write_text(
        json.dumps(_marketplace_payload(), ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )


def package_local_plugin(output: Path, *, force: bool = False) -> Path:
    destination = output.expanduser().resolve()
    if destination == PROJECT_ROOT or destination in PROJECT_ROOT.parents:
        raise ValueError("Output cannot replace the project or one of its parent directories")

    if destination.exists():
        if not force:
            raise FileExistsError(
                f"Output already exists: {destination}. Use --force only for a generated "
                f"{MARKETPLACE_NAME} marketplace."
            )
        if not destination.is_dir() or not _is_owned_marketplace(destination):
            raise ValueError(
                f"Refusing to replace a directory not owned by {MARKETPLACE_NAME}: {destination}"
            )

    destination.parent.mkdir(parents=True, exist_ok=True)
    staging = Path(
        tempfile.mkdtemp(prefix=f".{destination.name}.tmp-", dir=destination.parent)
    )
    try:
        _copy_bundle(staging)
        if destination.exists():
            shutil.rmtree(destination)
        staging.replace(destination)
    except Exception:
        shutil.rmtree(staging, ignore_errors=True)
        raise
    return destination


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Package AgentBoard as a compact local Codex marketplace."
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=PROJECT_ROOT / "dist" / "agentboard-marketplace",
        help="Destination marketplace root (default: dist/agentboard-marketplace).",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Replace an existing marketplace generated by this script.",
    )
    args = parser.parse_args()

    try:
        destination = package_local_plugin(args.output, force=args.force)
    except (FileExistsError, OSError, ValueError) as exc:
        parser.error(str(exc))

    print(f"Marketplace: {destination}")
    print(f"Plugin: {destination / 'plugins' / PLUGIN_NAME}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
